# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'

target 'ToDoPlanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToDoPlanner
  pod 'RealmSwift'
  pod 'SwipeCellKit'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/luckychris/Chameleon.git', :inhibit_warnings => true

  target 'ToDoPlannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToDoPlannerUITests' do
    # Pods for testing
  end

end
